### ISSUE TITLE
Option to Open Bookmark Manager in new window

### ISSUE THREAD

**Issue by sanicki** [ShoichiHirakawa/OpenBookmarkManager#1]
Can you please add an option to open Bookmark Manager in a new window as opposed to a new tab?

**Comment by ShoichiHirakawa** [comment]
Good, because I will work on the day off
Please wait ~

**Comment by ShoichiHirakawa** [comment]
I updated the option to open the bookmark manager in a new tab or a new window on the option page.

**Comment by sanicki** [comment]
Working perfectly. Thank you!
